CREATE TABLE BANDS(
    NAME VARCHAR(50) PRIMARY KEY,
    FORMATION_DATE DATE NULL
);

CREATE TABLE INSTRUMENTS(
    TYPE VARCHAR(50) PRIMARY KEY
);

CREATE TABLE MUSICIANS(
    NAME VARCHAR(50) PRIMARY KEY,
    BAND NOT NULL REFERENCES BANDS(NAME),
    INSTRUMENT NOT NULL REFERENCES INSTRUMENTS(TYPE),
    NATIONALITY VARCHAR(3) NULL
);

CREATE TABLE PLACES(
    NAME VARCHAR(50),
    CITY VARCHAR(50),
    COUNTRY VARCHAR(3) NULL,
    PRIMARY KEY(NAME, CITY)
);

CREATE TABLE CONCERTS(
    BAND REFERENCES BANDS(NAME),
    PLACE_NAME VARCHAR(50),
    CITY VARCHAR(50),
    CONCERT_DATE DATE NOT NULL,
    TOUR VARCHAR(50) NULL,
    FOREIGN KEY(PLACE_NAME, CITY) REFERENCES PLACES(NAME, CITY),
    PRIMARY KEY(BAND, PLACE_NAME, CITY, CONCERT_DATE)
);

CREATE TABLE FESTIVALS(
    NAME VARCHAR(50),
    DATE_START DATE,
    PLACE_NAME VARCHAR(50) NOT NULL,
    CITY VARCHAR(50) NOT NULL,
    FOREIGN KEY(PLACE_NAME, CITY) REFERENCES PLACES(NAME, CITY),
    PRIMARY KEY(NAME, DATE_START)
);

CREATE TABLE APPEARANCES(
    FESTIVAL_NAME VARCHAR(50),
    FESTIVAL_DATE_START DATE,
    BAND REFERENCES BANDS(NAME),
    FOREIGN KEY(FESTIVAL_NAME, FESTIVAL_DATE_START) REFERENCES FESTIVALS(NAME, DATE_START),
    PRIMARY KEY(BAND, FESTIVAL_NAME, FESTIVAL_DATE_START)
);

CREATE TABLE GENRES(
    NAME VARCHAR(50) PRIMARY KEY,
    SUPERGENRE NULL REFERENCES GENRES(NAME)
);

CREATE TABLE ALBUMS(
    BAND REFERENCES BANDS(NAME),
    NAME VARCHAR(50),
    GENRE NULL REFERENCES GENRES(NAME),
    PRIMARY KEY(BAND, NAME)
);

CREATE TABLE SONGS(
    BAND VARCHAR(50),
    ALBUM VARCHAR(50),
    POSITION NUMBER(2),
    NAME VARCHAR(50) NOT NULL,
    LENGTH NUMBER(4) NULL,
    FOREIGN KEY(ALBUM, BAND) REFERENCES ALBUMS(NAME, BAND),
    PRIMARY KEY(BAND, ALBUM, POSITION)
);

CREATE TABLE AWARDS(
    NAME VARCHAR(50) PRIMARY KEY
);

CREATE TABLE AWARD_RECEPTIONS(
    BAND VARCHAR(50),
    ALBUM VARCHAR(50),
    AWARD NOT NULL REFERENCES AWARDS(NAME),
    FOREIGN KEY(BAND, ALBUM) REFERENCES ALBUMS(BAND, NAME),
    PRIMARY KEY(BAND, ALBUM, AWARD)
);


DROP TABLE AWARD_RECEPTIONS;
DROP TABLE AWARDS;
DROP TABLE SONGS;
DROP TABLE ALBUMS;
DROP TABLE GENRES;
DROP TABLE MUSICIANS;
DROP TABLE INSTRUMENTS;
DROP TABLE APPEARANCES;
DROP TABLE FESTIVALS;
DROP TABLE CONCERTS;
DROP TABLE PLACES;
DROP TABLE BANDS;
